Pages:
  '1': |-
    This is a draft put out by my editor, I am still writing the thing.§0
    §0
    §0[Editors note - the pages will update automatically]§0
    §0
    §0
    §0...
  '2': and here is page 2